export interface Material {
  id: string;
  name: string;
  fam: string;
  note: string;
  desc: string;
  ifra: number | null;
  rMin: number;
  rMax: number;
  indolic: boolean;
  sens: boolean;
  tenacity: number | null;
  impact: number | null;
  cas?: string;
  role?: string;
  subFam?: string;
  preDil?: boolean;
  tenacityTier?: string;
  percepFactor?: number;
  dataSource?: string;
}

export const MATERIALS_DB: Material[] = [
// ALDEHYDES + ESTERS
{id:'aldc8',name:'Ald C8',fam:'Aldehydes+Esters',note:'top',desc:'Waxy citrus orange peel, powerful',ifra:null,rMin:.01,rMax:.3,indolic:false,sens:false,tenacity:7,impact:1000},
{id:'aldc9',name:'Ald C9',fam:'Aldehydes+Esters',note:'top',desc:'Rose waxy, floral, cucumber facet',ifra:null,rMin:.01,rMax:.3,indolic:false,sens:false,tenacity:276,impact:550},
{id:'aldc10',name:'Ald C10',fam:'Aldehydes+Esters',note:'top',desc:'Citrus orange, waxy, classic Chanel note',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:224,impact:500},
{id:'aldc11',name:'Ald C11',fam:'Aldehydes+Esters',note:'top',desc:'Fresh soapy floral, clean aldehydic',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:48,impact:175},
{id:'aldc12_lauric',name:'Ald C12 Lauric',fam:'Aldehydes+Esters',note:'top',desc:'Waxy soapy, slightly floral',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:380,impact:700},
{id:'aldc12_mna',name:'Ald C12 MNA',fam:'Aldehydes+Esters',note:'top',desc:'Clean floral, muguet, powdery',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:388,impact:700},
{id:'aldc14_peach',name:'Ald C14 Peach',fam:'Aldehydes+Esters',note:'heart',desc:'Peach apricot, slightly coconut',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:340,impact:360},
{id:'aldc19',name:'Ald C19',fam:'Aldehydes+Esters',note:'heart',desc:'Fresh aldehydic, iris-like, powdery',ifra:null,rMin:.05,rMax:.5,indolic:false,sens:false,tenacity:null,impact:null},
{id:'allyl_amyl_glycolate',name:'Allyl Amyl Glycolate',fam:'Aldehydes+Esters',note:'top',desc:'Pineapple-green, powerful — Cat4: 0.002%',ifra:.002,rMin:.0002,rMax:.002,indolic:false,sens:true,tenacity:84,impact:170},
{id:'allyl_caproate_c6',name:'Allyl Caproate C6',fam:'Aldehydes+Esters',note:'top',desc:'Pineapple, tropical, fruity',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:1,impact:250,cas:'123-68-2'},
{id:'benzyl_acetate',name:'Benzyl Acetate',fam:'Aldehydes+Esters',note:'heart',desc:'Jasmine, floral, fruity sweet — Cat4: 7%',ifra:7,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:4,impact:120},
{id:'benzyl_benzoate',name:'Benzyl Benzoate',fam:'Aldehydes+Esters',note:'base',desc:'Faint balsamic, fixative solvent',ifra:null,rMin:.5,rMax:15,indolic:false,sens:true,tenacity:322,impact:18},
{id:'benzyl_salicylate',name:'Benzyl Salicylate',fam:'Aldehydes+Esters',note:'base',desc:'Soft balsamic floral fixer — Cat4: 2%',ifra:2,rMin:.5,rMax:5,indolic:false,sens:true,tenacity:384,impact:30},
{id:'iso_amyl_salicylate',name:'Iso Amyl Salicylate',fam:'Aldehydes+Esters',note:'base',desc:'Clover sweet faint floral — Cat4: 1%',ifra:1,rMin:.2,rMax:3,indolic:false,sens:true,tenacity:124,impact:110},
// MUSKS
{id:'habanolide',name:'Habanolide',fam:'Musks',note:'base',desc:'Macrocyclic musk, clean, smooth',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:400,impact:100},
{id:'galaxolide_undil',name:'Galaxolide Undil',fam:'Musks',note:'base',desc:'Powdery clean woody musk — Cat4: 5.3%',ifra:5.3,rMin:1,rMax:10,indolic:false,sens:false,tenacity:400,impact:60},
{id:'timbersilk',name:'Timbersilk',fam:'Musks',note:'base',desc:'Woody clean silky musk',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:172,impact:null},
{id:'velvione',name:'Velvione',fam:'Musks',note:'base',desc:'Macrocyclic, velvety warm musk',ifra:null,rMin:1,rMax:8,indolic:false,sens:false,tenacity:720,impact:25},
{id:'romandolide',name:'Romandolide',fam:'Musks',note:'base',desc:'Macrocyclic, creamy soft musk',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:400,impact:100},
{id:'timberol',name:'Timberol',fam:'Musks',note:'base',desc:'Sandalwood-musk, creamy woody',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:10,impact:100},
{id:'ethylene_brassylate',name:'Ethylene Brassylate',fam:'Musks',note:'base',desc:'Macrocyclic, sweet clean musk',ifra:null,rMin:1,rMax:12,indolic:false,sens:false,tenacity:280,impact:40},
{id:'muscenone_delta',name:'Muscenone Delta',fam:'Musks',note:'base',desc:'Macrocyclic, musky subtle skin',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:400,impact:null},
{id:'ambrofix_powder',name:'Ambrofix Powder',fam:'Musks',note:'base',desc:'Ambergris, woody warm diffusive',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:720,impact:200},
{id:'helvetolide',name:'Helvetolide',fam:'Musks',note:'base',desc:'Fruity musk, pear-like, clean',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:400,impact:100},
{id:'musk_ketone',name:'Musk Ketone',fam:'Musks',note:'base',desc:'Nitro musk, powdery (restricted) — Cat4: 0.07%',ifra:.07,rMin:.005,rMax:.07,indolic:false,sens:true,tenacity:400,impact:35},
{id:'exaltolide_total',name:'Exaltolide Total',fam:'Musks',note:'base',desc:'Macrocyclic, classic exaltolide',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:400,impact:25},
{id:'ambrettolide',name:'Ambrettolide',fam:'Musks',note:'base',desc:'Macrocyclic, natural-seeming musk',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:172,impact:30},
{id:'tonalide',name:'Tonalide',fam:'Musks',note:'base',desc:'Polycyclic musk (restricted) — Cat4: 0.03%',ifra:.03,rMin:.005,rMax:.03,indolic:false,sens:true,tenacity:400,impact:20},
{id:'exaltolide',name:'Exaltolide',fam:'Musks',note:'base',desc:'Macrocyclic musk, warm smooth',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:400,impact:25},
{id:'edenolide',name:'Edenolide',fam:'Musks',note:'base',desc:'Macrocyclic, fruity creamy musk',ifra:null,rMin:1,rMax:8,indolic:false,sens:false,tenacity:148,impact:100},
{id:'ambrocenide',name:'Ambrocenide',fam:'Musks',note:'base',desc:'Macrocyclic, woody smoky musk',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:400,impact:100},
{id:'ambrettolide_iff',name:'Ambrettolide IFF',fam:'Musks',note:'base',desc:'IFF version, macrocyclic natural',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:172,impact:30},
{id:'ambrox_super',name:'Ambrox Super',fam:'Musks',note:'base',desc:'Ambergris, warm woody diffusive',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:750,impact:500},
{id:'globanone_50_dpg',name:'Globanone 50 DPG',fam:'Musks',note:'base',desc:'Macrocyclic musk 50% in DPG',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:260,impact:null},
{id:'globalide',name:'Globalide',fam:'Musks',note:'base',desc:'Macrocyclic, smooth clean musk',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:350,impact:null},
{id:'sbq',name:'SBQ',fam:'Musks',note:'base',desc:'Macrocyclic musk, clean diffusive',ifra:null,rMin:1,rMax:8,indolic:false,sens:false,tenacity:null,impact:null},
// PATCHOULI + VETIVER
{id:'vetiveryl_acetate',name:'Vetiveryl Acetate',fam:'Patchouli+Vetiver',note:'base',desc:'Vetiver ester, woody smoky dry',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:360,impact:80},
{id:'patchouli_aura',name:'Patchouli Aura Cacia',fam:'Patchouli+Vetiver',note:'base',desc:'Natural patchouli, earthy camphor',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:400,impact:98},
{id:'patchouli_light',name:'Patchouli Light EO',fam:'Patchouli+Vetiver',note:'base',desc:'Light patchouli, less earthy, softer',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:400,impact:100},
{id:'vetiver_eo',name:'Vetiver EO',fam:'Patchouli+Vetiver',note:'base',desc:'Smoky woody earthy, clean drydown',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:400,impact:105},
{id:'cypriol_eo',name:'Cypriol EO',fam:'Patchouli+Vetiver',note:'base',desc:'Smoky, woody, oud-like, dry',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:2.5,impact:110},
{id:'patchouli_dark',name:'Patchouli Dark',fam:'Patchouli+Vetiver',note:'base',desc:'Dark patchouli, heavy earthy deep',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:98},
// CITRUS
{id:'lemon',name:'Lemon',fam:'Citrus',note:'top',desc:'Fresh bright lemon, ~5% citral',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:4,impact:130},
{id:'sweet_orange',name:'Sweet Orange',fam:'Citrus',note:'top',desc:'Sweet juicy orange, clean fresh',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:4,impact:110},
{id:'citral',name:'Citral',fam:'Citrus',note:'top',desc:'Pure lemon-lime, 100% citral — Cat4: 1.0%',ifra:1,rMin:.1,rMax:1,indolic:false,sens:true,tenacity:12,impact:270},
{id:'methyl_pamplemousse',name:'Methyl Pamplemousse',fam:'Citrus',note:'top',desc:'Synthetic grapefruit, fresh rosy',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:3,impact:0},
{id:'bergamot_fcr',name:'Bergamot FCR',fam:'Citrus',note:'top',desc:'Bergamot furocoumarin-free, no phototoxic risk',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:8,impact:100},
{id:'blood_orange',name:'Blood Orange',fam:'Citrus',note:'top',desc:'Sweet orange with berry facet',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:4,impact:100},
{id:'petitgrain',name:'Petitgrain',fam:'Citrus',note:'top',desc:'Woody citrus, herbal green-floral',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:28,impact:110},
{id:'grapefruit',name:'Grapefruit',fam:'Citrus',note:'top',desc:'Tart fresh, slightly bitter grapefruit',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:16,impact:125},
{id:'lime_eo',name:'Lime EO',fam:'Citrus',note:'top',desc:'Sharp citrus-lime, fresh, ~6% citral',ifra:null,rMin:2,rMax:15,indolic:false,sens:false,tenacity:20,impact:300},
{id:'lemongrass',name:'Lemongrass',fam:'Citrus',note:'top',desc:'Lemony-grassy, ~70% citral — Cat4: 0.7%',ifra:.7,rMin:.05,rMax:.7,indolic:false,sens:true,tenacity:11,impact:150},
{id:'mandarin',name:'Mandarin',fam:'Citrus',note:'top',desc:'Sweet tangy mandarin, diffusive',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:4,impact:90},
{id:'citronellal',name:'Citronellal',fam:'Citrus',note:'top',desc:'Rosy-citronella — IFRA Cat4: 0.6%',ifra:.6,rMin:.05,rMax:.6,indolic:false,sens:true,tenacity:16,impact:380},
// LAV + AROMATIC
{id:'clary_sage_eo',name:'Clary Sage EO',fam:'Lav+Aromatic',note:'heart',desc:'Herbaceous, slightly sweet amber facet',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:48,impact:105},
{id:'linalool_natural',name:'Linalool Natural',fam:'Lav+Aromatic',note:'heart',desc:'Rose-woody soft floral, EU allergen',ifra:24,rMin:.5,rMax:15,indolic:false,sens:true,tenacity:12,impact:100},
{id:'cedar_leaf_eo',name:'Cedar Leaf EO',fam:'Lav+Aromatic',note:'top',desc:'Fresh camphorous, green woody',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:30,impact:220},
{id:'lavender_eo',name:'Lavender EO',fam:'Lav+Aromatic',note:'heart',desc:'Classic lavender, floral herbal fresh',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:27,impact:110},
{id:'lavandin_eo',name:'Lavandin EO',fam:'Lav+Aromatic',note:'heart',desc:'Camphoraceous lavender, slightly harsh',ifra:null,rMin:2,rMax:15,indolic:false,sens:false,tenacity:4,impact:110},
{id:'linalyl_acetate',name:'Linalyl Acetate',fam:'Lav+Aromatic',note:'heart',desc:'Fresh bergamot-floral, key lavender ester',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:20,impact:110},
{id:'red_thyme_eo',name:'Red Thyme EO',fam:'Lav+Aromatic',note:'top',desc:'Herbal spicy-phenolic, powerful — Cat4: 0.5%',ifra:.5,rMin:.05,rMax:.5,indolic:false,sens:true,tenacity:35,impact:570},
{id:'menthol_crystal',name:'Menthol Crystal',fam:'Lav+Aromatic',note:'top',desc:'Intensely cooling, peppermint minty',ifra:null,rMin:.1,rMax:2,indolic:false,sens:false,tenacity:32,impact:120},
{id:'lavender_4042',name:'Lavender 40/42',fam:'Lav+Aromatic',note:'heart',desc:'Standardised lavender, consistent quality',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:27,impact:110},
{id:'ethyl_linalool',name:'Ethyl Linalool',fam:'Lav+Aromatic',note:'heart',desc:'Fresh slightly green linalool variant',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:30,impact:100},
{id:'linalool_coeur',name:'Linalool Coeur',fam:'Lav+Aromatic',note:'heart',desc:'Rosewood-woody, clean floral linalool',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:12,impact:100},
// JASMINE + HEDIONE
{id:'heliotropin_x24',name:'Heliotropin X24',fam:'Jasmine+Hedione',note:'heart',desc:'Powdery heliotrope, almond-cherry-vanilla',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:400,impact:90},
{id:'hedione',name:'Hedione',fam:'Jasmine+Hedione',note:'heart',desc:'Diffusive jasmine, fresh clean, revolutionary',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:168,impact:65},
{id:'hedione_hc',name:'Hedione HC',fam:'Jasmine+Hedione',note:'heart',desc:'High-cis hedione, stronger more floral',ifra:null,rMin:2,rMax:20,indolic:false,sens:false,tenacity:720,impact:65},
{id:'helional',name:'Helional',fam:'Jasmine+Hedione',note:'heart',desc:'Lily-of-the-valley, fresh marine floral',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:60,impact:80},
// FLORALS + MUGUET
{id:'rose_givco217',name:'Rose Givco 217',fam:'Florals+Muguet',note:'heart',desc:'Rose base accord, full-bodied warm',ifra:null,rMin:1,rMax:15,indolic:false,sens:false,tenacity:null,impact:null},
{id:'rose_oxide_hc',name:'Rose Oxide HC',fam:'Florals+Muguet',note:'top',desc:'Key rose oxide, geranium-rosy, powerful',ifra:null,rMin:.001,rMax:.1,indolic:false,sens:false,tenacity:8,impact:700},
{id:'melonal',name:'Melonal',fam:'Florals+Muguet',note:'top',desc:'Watermelon, cucumber, fresh green',ifra:null,rMin:.1,rMax:2,indolic:false,sens:false,tenacity:160,impact:700},
{id:'rose_absolute',name:'Rose Absolute',fam:'Florals+Muguet',note:'heart',desc:'Natural rose, rich waxy complex',ifra:null,rMin:.2,rMax:5,indolic:false,sens:true,tenacity:24,impact:250},
{id:'sambac_floraline',name:'Sambac Floraline',fam:'Florals+Muguet',note:'heart',desc:'Jasmine sambac accord, creamy indolic',ifra:null,rMin:.5,rMax:8,indolic:true,sens:false,tenacity:45,impact:145},
{id:'aurantiol',name:'Aurantiol',fam:'Florals+Muguet',note:'heart',desc:'Orange blossom, methyl anthranilate-based — Cat4: ~0.2%',ifra:.2,rMin:.05,rMax:.5,indolic:true,sens:true,tenacity:300,impact:44},
{id:'jasmine_floraline',name:'Jasmine Floraline',fam:'Florals+Muguet',note:'heart',desc:'Jasmine accord, clean diffusive floral',ifra:null,rMin:.5,rMax:10,indolic:true,sens:false,tenacity:45,impact:170},
{id:'florol',name:'Florol',fam:'Florals+Muguet',note:'heart',desc:'Lily-of-the-valley, clean watery',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:24,impact:100},
{id:'magnolia_floraline',name:'Magnolia Floraline',fam:'Florals+Muguet',note:'heart',desc:'Magnolia accord, citrusy-floral soft',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:null,impact:null},
{id:'hydroxycitronellal',name:'Hydroxycitronellal',fam:'Florals+Muguet',note:'heart',desc:'Muguet-linden, sweet floral — Cat4: 1.0%',ifra:1,rMin:.2,rMax:3,indolic:false,sens:true,tenacity:192,impact:25},
{id:'lilyflore',name:'Lilyflore',fam:'Florals+Muguet',note:'heart',desc:'Lily, clean slightly green floral',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:720,impact:null},
{id:'triplamour',name:'Triplamour',fam:'Florals+Muguet',note:'heart',desc:'Floral slightly powdery, modern',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:null,impact:null},
{id:'tuberose_floraline75',name:'Tuberose Floraline 75',fam:'Florals+Muguet',note:'heart',desc:'Rich tuberose accord, creamy dense',ifra:null,rMin:.5,rMax:8,indolic:true,sens:false,tenacity:36,impact:250},
{id:'neroli_eo',name:'Neroli EO',fam:'Florals+Muguet',note:'heart',desc:'Orange blossom, fresh floral bitter',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:120,impact:120},
{id:'nerolidol',name:'Nerolidol',fam:'Florals+Muguet',note:'heart',desc:'Rose-apple-green, woody facet, fresh',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:100,impact:38},
{id:'hexyl_cinnamic_ald',name:'Hexyl Cinnamic Aldehyde',fam:'Florals+Muguet',note:'heart',desc:'Jasmine, warm floral, HCA — Cat4: 5.6%',ifra:5.6,rMin:.5,rMax:8,indolic:false,sens:true,tenacity:400,impact:100},
{id:'nympheal',name:'Nympheal',fam:'Florals+Muguet',note:'heart',desc:'Lily-of-the-valley, clean aquatic-floral',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:700,impact:100},
{id:'mayol',name:'Mayol',fam:'Florals+Muguet',note:'heart',desc:'Muguet, clean slightly rosy lily',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:24,impact:100},
{id:'coranol',name:'Coranol',fam:'Florals+Muguet',note:'heart',desc:'Rosy-muguet, clean fresh floral',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:20,impact:null},
{id:'bourgeonal',name:'Bourgeonal',fam:'Florals+Muguet',note:'heart',desc:'Powerful muguet (restricted) — Cat4: 0.01%',ifra:.01,rMin:.001,rMax:.01,indolic:false,sens:true,tenacity:100,impact:80},
{id:'methyl_diantilis',name:'Methyl Diantilis',fam:'Florals+Muguet',note:'heart',desc:'Carnation, clove-spicy floral',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:400,impact:100},
// IRIS + IONONES
{id:'orris_root_abs',name:'Orris Root Abs',fam:'Iris+Ionones',note:'heart',desc:'Orris, powdery violet carroty',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:296,impact:40},
{id:'ionone_beta',name:'Ionone Beta',fam:'Iris+Ionones',note:'heart',desc:'Woody violet, iris, slightly sweet',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:48,impact:120},
{id:'methyl_ionone_gamma',name:'Methyl Ionone Gamma EQ',fam:'Iris+Ionones',note:'heart',desc:'Soft violet-iris, powdery warm',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:124,impact:90},
{id:'methyl_ionone_alpha',name:'Methyl Ionone Alpha',fam:'Iris+Ionones',note:'heart',desc:'Violet-iris, woody Orris character',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:124,impact:90},
{id:'ionone_alpha',name:'Ionone Alpha',fam:'Iris+Ionones',note:'heart',desc:'Floral violet, sweet fresh',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:48,impact:100},
{id:'dihydro_ionone_beta',name:'Dihydro Ionone Beta',fam:'Iris+Ionones',note:'heart',desc:'Woody iris, slightly smoky',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:9,impact:220},
{id:'isoraldeine_95',name:'Isoraldeine 95',fam:'Iris+Ionones',note:'heart',desc:'Powerful iris-violet, metallic facet',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:124,impact:null},
{id:'orris_base_givco',name:'Orris Base Givco',fam:'Iris+Ionones',note:'heart',desc:'Givco orris accord, powdery floral',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:28,impact:40},
// MUSK SPECIALTIES
{id:'herbanate',name:'Herbanate',fam:'Musk Specialties',note:'base',desc:'Woody-green musk, spirene-like character',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:72,impact:null},
{id:'norlimbanol',name:'Norlimbanol',fam:'Musk Specialties',note:'base',desc:'Sandalwood-musk, powerful woody',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:300,impact:1000},
{id:'ambrette_abs',name:'Ambrette Abs India',fam:'Musk Specialties',note:'base',desc:'Natural musk seed, musky wine-like',ifra:null,rMin:.1,rMax:2,indolic:false,sens:false,tenacity:332,impact:94},
// GOURMAND
{id:'anethole',name:'Anethole',fam:'Gourmand',note:'heart',desc:'Anise, sweet, liquorice, herbal-sweet',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:null,impact:null},
{id:'ethyl_vanillin',name:'Ethyl Vanillin',fam:'Gourmand',note:'base',desc:'Vanilla 3× stronger than vanillin',ifra:null,rMin:.05,rMax:2,indolic:false,sens:false,tenacity:400,impact:600},
{id:'fructone',name:'Fructone',fam:'Gourmand',note:'heart',desc:'Fruity, apple, pineapple tropical',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:72,impact:80},
{id:'coumarin',name:'Coumarin',fam:'Gourmand',note:'base',desc:'Hay, tonka, sweet — IFRA Cat4: 2.18%',ifra:2.18,rMin:.5,rMax:3,indolic:false,sens:false,tenacity:364,impact:120},
{id:'tonka_abs',name:'Tonka Bean Abs 20 DPG',fam:'Gourmand',note:'base',desc:'Tonka, vanilla-coumarin, sweet almond',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:364,impact:260},
{id:'ethyl_maltol',name:'Ethyl Maltol',fam:'Gourmand',note:'base',desc:'Cotton candy, caramel, sweet fruity',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:360,impact:2500},
{id:'raspberry_ketone',name:'Raspberry Ketone',fam:'Gourmand',note:'heart',desc:'Raspberry, fruity, rosy facet',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:336,impact:70},
{id:'vanillin',name:'Vanillin',fam:'Gourmand',note:'base',desc:'Classic vanilla, sweet warm balsamic',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:400,impact:60},
{id:'vanillin_sig',name:'Vanillin Sig',fam:'Gourmand',note:'base',desc:'Signature vanillin, pure high quality',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:400,impact:60},
{id:'vanillin_isobutyrate',name:'Vanillin Iso Butyrate',fam:'Gourmand',note:'base',desc:'Vanilla ester, creamy slightly floral',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:400,impact:null},
{id:'yara_yara',name:'Yara Yara',fam:'Gourmand',note:'heart',desc:'Beta-naphthyl methyl ether, neroli-cherry',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:null,impact:null},
{id:'tonquitone',name:'Tonquitone',fam:'Gourmand',note:'base',desc:'Muguet-tonka, sweet coumarinic floral',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:300,impact:null},
// ANIMALICS
{id:'castoreum_givco',name:'Castoreum Givco 116',fam:'Animalics',note:'base',desc:'Leather-animalic castoreum type',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:null,impact:null},
{id:'indole',name:'Indole',fam:'Animalics',note:'heart',desc:'Jasmine-animalic-fecal — IFRA Cat4: 0.1%',ifra:.1,rMin:.005,rMax:.1,indolic:true,sens:false,tenacity:400,impact:700},
{id:'civette_givco',name:'Civette Givco 208',fam:'Animalics',note:'base',desc:'Civet accord, animalic musky-fecal',ifra:null,rMin:.05,rMax:1,indolic:true,sens:false,tenacity:null,impact:null},
{id:'creosol',name:'Creosol',fam:'Animalics',note:'base',desc:'Smoky tarry phenolic, leather character',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:132,impact:null},
// TOBACCO
{id:'veramoss',name:'Veramoss',fam:'Tobacco',note:'base',desc:'Oakmoss substitute, mossy green',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:360,impact:null},
{id:'coffee_co2',name:'Coffee CO2',fam:'Tobacco',note:'heart',desc:'Rich roasted coffee, dark bittersweet',ifra:null,rMin:.2,rMax:3,indolic:false,sens:false,tenacity:400,impact:150},
{id:'oakmoss_abs',name:'Oakmoss Abs',fam:'Tobacco',note:'base',desc:'Classic chypre material — IFRA Cat4: 0.1%',ifra:.1,rMin:.01,rMax:.1,indolic:false,sens:true,tenacity:400,impact:125},
{id:'tobacco_abs',name:'Tobacco Abs',fam:'Tobacco',note:'base',desc:'Natural tobacco, smoky dried herb',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:36,impact:400},
// ROSE
{id:'nerol_90',name:'Nerol 90',fam:'Rose',note:'heart',desc:'Rosy fresh, neroli facet geranium',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:24,impact:100},
{id:'geranium_eo',name:'Geranium EO',fam:'Rose',note:'heart',desc:'Rose-green, herbal fresh complex',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:8,impact:170},
{id:'citronellol',name:'Citronellol',fam:'Rose',note:'heart',desc:'Rosy fresh sweet — IFRA Cat4: 5.3%',ifra:5.3,rMin:.5,rMax:8,indolic:false,sens:true,tenacity:48,impact:100},
{id:'phenyl_ethyl_alc',name:'Phenyl Ethyl Alcohol',fam:'Rose',note:'heart',desc:'Core rose alcohol — IFRA Cat4: 6.3%',ifra:6.3,rMin:1,rMax:10,indolic:false,sens:false,tenacity:32,impact:60},
{id:'geraniol_extra',name:'Geraniol Extra',fam:'Rose',note:'heart',desc:'Rose-geranium ~98% geraniol — Cat4: 2.2%',ifra:2.2,rMin:.5,rMax:5,indolic:false,sens:true,tenacity:60,impact:100},
{id:'phenoxanol',name:'Phenoxanol',fam:'Rose',note:'heart',desc:'Rosy, muguet-facet, clean smooth',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:100},
// NATURALS
{id:'honeysuckle_abs',name:'Honeysuckle Abs',fam:'Naturals',note:'heart',desc:'Natural honeysuckle, sweet diffusive',ifra:null,rMin:.2,rMax:3,indolic:false,sens:false,tenacity:null,impact:null},
{id:'ylang_ylang_eo',name:'Ylang Ylang 1+3 EO',fam:'Naturals',note:'heart',desc:'Heavy floral, indolic — IFRA Cat4: 0.6%',ifra:.6,rMin:.05,rMax:.6,indolic:true,sens:true,tenacity:140,impact:120},
{id:'javanol',name:'Javanol',fam:'Naturals',note:'base',desc:'Sandalwood, creamy milky precious',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:250},
{id:'tagetes_abs',name:'Tagetes Abs',fam:'Naturals',note:'heart',desc:'Marigold green-fruity — IFRA Cat4: 0.01%',ifra:.01,rMin:.001,rMax:.01,indolic:false,sens:true,tenacity:25,impact:100},
{id:'green_tea_abs',name:'Green Tea Abs',fam:'Naturals',note:'heart',desc:'Fresh green tea, vegetal clean',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:0,impact:150},
{id:'rosewood_eo',name:'Rosewood EO',fam:'Naturals',note:'heart',desc:'Floral rosewood, linalool-rich smooth',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:12,impact:100},
{id:'elemi_eo',name:'Elemi EO+Resinoid 50BB',fam:'Naturals',note:'heart',desc:'Citrus-resinous, spicy, frankincense',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:50,impact:120},
// LEATHER
{id:'birch_tar',name:'Birch Tar Rect',fam:'Leather',note:'base',desc:'Smoky leather, tarry medicinal — Cat4: 1%',ifra:1,rMin:.05,rMax:1,indolic:false,sens:true,tenacity:400,impact:1200},
{id:'isobutyl_quinoline',name:'Isobutyl Quinoline',fam:'Leather',note:'base',desc:'Leather, quinoline, smoky dry',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:50,impact:450},
{id:'eugenol',name:'Eugenol USP',fam:'Leather',note:'heart',desc:'Clove spice, warm — IFRA Cat4: 0.5%',ifra:.5,rMin:.05,rMax:.5,indolic:false,sens:true,tenacity:52,impact:175},
{id:'suederal',name:'Suederal LT',fam:'Leather',note:'base',desc:'Suede leather, smooth modern',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:168,impact:250},
{id:'guaiacol',name:'Guaiacol',fam:'Leather',note:'base',desc:'Smoky, phenolic, medicinal-leather',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:280,impact:1250},
// WOODS
{id:'sandalwood_australia',name:'Sandalwood Australia EO',fam:'Woods',note:'base',desc:'Creamy sandalwood, buttery precious',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:999,impact:70},
{id:'agarwood_black_rco',name:'Agarwood Black RCO',fam:'Woods',note:'base',desc:'Oud, smoky dark animalic-woody',ifra:null,rMin:.2,rMax:3,indolic:false,sens:false,tenacity:480,impact:120},
{id:'cedarwood_atlas',name:'Cedarwood Atlas EO',fam:'Woods',note:'base',desc:'Warm cedar, slightly sweet classic',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:192,impact:null},
{id:'iso_e_super',name:'Iso E Super',fam:'Woods',note:'base',desc:'Cedar-cyclo, skin-close, pheromonic',ifra:null,rMin:1,rMax:20,indolic:false,sens:false,tenacity:280,impact:40},
{id:'olibanol',name:'Olibanol',fam:'Woods',note:'base',desc:'Frankincense/olibanum, balsamic resin',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:400,impact:null},
{id:'guaiac_wood',name:'Guaiac Wood',fam:'Woods',note:'base',desc:'Smoky, rosy-woody, tea-like',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:60,impact:1250},
{id:'olibanum_abs',name:'Olibanum Abs',fam:'Woods',note:'base',desc:'Natural frankincense absolute',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:null,impact:null},
{id:'sandalore',name:'Sandalore',fam:'Woods',note:'base',desc:'Synthetic sandalwood, creamy woody',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:null,impact:null},
{id:'polysantol',name:'Polysantol',fam:'Woods',note:'base',desc:'Sandalwood, milky soft creamy',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:336,impact:100},
{id:'hindinol',name:'Hindinol',fam:'Woods',note:'base',desc:'Sandalwood, powerful lasting',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:400,impact:100},
{id:'oud_synth',name:'Oud Synth 184007',fam:'Woods',note:'base',desc:'Synthetic oud, smoky dark-woody',ifra:null,rMin:.2,rMax:3,indolic:false,sens:false,tenacity:480,impact:100},
{id:'bacdanol',name:'Bacdanol',fam:'Woods',note:'base',desc:'Sandalwood type, clean smooth',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:336,impact:80},
{id:'clearwood',name:'Clearwood',fam:'Woods',note:'base',desc:'Vetiver-patchouli-woody, clean',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:168,impact:null},
{id:'vertofix_coeur',name:'Vertofix Coeur',fam:'Woods',note:'base',desc:'Woody-cedar, smooth slightly spicy',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:70},
{id:'ebanol',name:'Ebanol',fam:'Woods',note:'base',desc:'Sandalwood, slightly green creamy',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:125},
{id:'cedryl_acetate',name:'Cedryl Acetate Liquid',fam:'Woods',note:'base',desc:'Cedar ester, warm smooth woody',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:60},
{id:'kephalis',name:'Kephalis',fam:'Woods',note:'base',desc:'Fir needle-cedar, dry cool conifer',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:80,impact:80},
{id:'sandela_85',name:'Sandela 85',fam:'Woods',note:'base',desc:'Sandalwood note by Givaudan',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:20},
{id:'amyris_eo',name:'Amyris EO',fam:'Woods',note:'base',desc:'Sandalwood substitute, woody creamy',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:2000,impact:120},
{id:'fir_needle_eo',name:'Fir Needle EO',fam:'Woods',note:'top',desc:'Fresh conifer, green clean',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:24,impact:125},
{id:'myrrh_co2',name:'Myrrh CO2',fam:'Woods',note:'base',desc:'Myrrh resin, balsamic spicy-woody',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:400,impact:60},
{id:'juniper_eo',name:'Juniper EO',fam:'Woods',note:'top',desc:'Fresh gin-like, piney clean',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:24,impact:200},
{id:'cypress_eo',name:'Cypress EO',fam:'Woods',note:'top',desc:'Fresh conifer, slightly herbal',ifra:null,rMin:1,rMax:10,indolic:false,sens:false,tenacity:44,impact:110},
{id:'fir_balsam_eo',name:'Fir Balsam EO',fam:'Woods',note:'base',desc:'Balsamic fir, warm resinous',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:12,impact:90},
// MISC
{id:'cinnamyl_alcohol',name:'Cinnamyl Alcohol',fam:'Misc',note:'heart',desc:'Hyacinth-cinnamon — IFRA Cat4: 0.6%',ifra:.6,rMin:.05,rMax:.6,indolic:false,sens:true,tenacity:371,impact:80},
{id:'ethyl_butyrate',name:'Ethyl Butyrate',fam:'Misc',note:'top',desc:'Fruity, apple, pineapple tropical',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:4,impact:460},
{id:'cinnamaldehyde',name:'Cinnamaldehyde',fam:'Misc',note:'heart',desc:'Cinnamon spice — IFRA Cat4: 0.07%',ifra:.07,rMin:.005,rMax:.07,indolic:false,sens:true,tenacity:75,impact:130},
{id:'damascenone',name:'Damascenone',fam:'Misc',note:'heart',desc:'Rose-apple ketone, extreme impact',ifra:null,rMin:.0001,rMax:.02,indolic:false,sens:false,tenacity:200,impact:500},
{id:'tec',name:'TEC (Triethyl Citrate)',fam:'Misc',note:'base',desc:'Plasticizer/solvent, odourless carrier',ifra:null,rMin:1,rMax:20,indolic:false,sens:false,tenacity:null,impact:null},
{id:'methyl_anthranilate',name:'Methyl Anthranilate',fam:'Misc',note:'heart',desc:'Grape, orange flower — IFRA Cat4: 0.1%',ifra:.1,rMin:.01,rMax:.1,indolic:true,sens:true,tenacity:88,impact:420},
{id:'bht',name:'BHT',fam:'Misc',note:'base',desc:'Antioxidant preservative, near-odourless',ifra:null,rMin:.01,rMax:.1,indolic:false,sens:false,tenacity:24,impact:1},
{id:'cassis_345b',name:'Cassis 345B',fam:'Misc',note:'top',desc:'Blackcurrant, green, sulphurous facet',ifra:null,rMin:.1,rMax:2,indolic:false,sens:false,tenacity:350,impact:null},
{id:'gamma_undecalactone',name:'Gamma Undecalactone',fam:'Misc',note:'heart',desc:'Peach, coconut, fruity creamy',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:340,impact:180},
{id:'damascone_abd',name:'Damascone ABD',fam:'Misc',note:'heart',desc:'Rose-apple-fruity ketone, powerful',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:null,impact:null},
{id:'galbanum_eo',name:'Galbanum EO',fam:'Misc',note:'top',desc:'Green, pine, resinous sharp',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:70,impact:600},
{id:'ambrinol',name:'Ambrinol',fam:'Misc',note:'base',desc:'Ambergris, woody warm diffusive',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:96,impact:null},
{id:'benzyl_alcohol',name:'Benzyl Alcohol',fam:'Misc',note:'heart',desc:'Faint almond-rose, solvent carrier',ifra:null,rMin:.5,rMax:15,indolic:false,sens:false,tenacity:35,impact:5},
{id:'carrot_seed_eo',name:'Carrot Seed EO',fam:'Misc',note:'heart',desc:'Warm earthy carrot, slightly woody',ifra:null,rMin:.2,rMax:3,indolic:false,sens:false,tenacity:100,impact:185},
{id:'triplal',name:'Triplal',fam:'Misc',note:'top',desc:'Aldehydic citrus-herbal, clean fresh',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:24,impact:800},
{id:'galbanum_resinoid',name:'Galbanum Resinoid',fam:'Misc',note:'base',desc:'Green-balsamic, resinous deep',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:400,impact:88},
{id:'cis_jasmone_lactone',name:'Cis Jasmone Lactone',fam:'Misc',note:'heart',desc:'Jasmine, clean floral fruity facet',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:60,impact:null},
{id:'dpg',name:'DPG',fam:'Misc',note:'base',desc:'Dipropylene glycol carrier, odourless',ifra:null,rMin:5,rMax:40,indolic:false,sens:false,tenacity:7,impact:3},
{id:'phenyl_acetaldehyde',name:'Phenyl Acetaldehyde',fam:'Misc',note:'heart',desc:'Hyacinth honey animalic — Cat4: 0.1%',ifra:.1,rMin:.005,rMax:.1,indolic:false,sens:false,tenacity:9.1,impact:42.7},
{id:'verdox_hc',name:'Verdox HC',fam:'Misc',note:'top',desc:'Cedar-woody, fresh green',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:30,impact:160},
{id:'styrax_storax',name:'Styrax/Storax',fam:'Misc',note:'base',desc:'Balsamic smoky, styrene-resin',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:400,impact:100},
{id:'anisic_aldehyde',name:'Anisic Aldehyde',fam:'Misc',note:'heart',desc:'Anise hawthorn sweet — Cat4: 0.1%',ifra:.1,rMin:.01,rMax:.1,indolic:false,sens:false,tenacity:50,impact:130},
{id:'dimethyl_anthranilate',name:'Dimethyl Anthranilate',fam:'Misc',note:'heart',desc:'Grape floral, gentler than methyl anth.',ifra:null,rMin:.1,rMax:2,indolic:true,sens:false,tenacity:50,impact:90},
{id:'iso_damascone',name:'Iso Damascone',fam:'Misc',note:'heart',desc:'Rose-plum-apple, powerful ketone',ifra:null,rMin:.005,rMax:.2,indolic:false,sens:false,tenacity:null,impact:null},
{id:'florhydral',name:'Florhydral',fam:'Misc',note:'top',desc:'Cyclamen, fresh aquatic-floral',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:144,impact:null},
{id:'styrallyl_acetate',name:'Styrallyl Acetate',fam:'Misc',note:'top',desc:'Gardenia, citrus-floral green',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:8,impact:350},
{id:'cassia_eo',name:'Cassia EO',fam:'Misc',note:'heart',desc:'Chinese cinnamon — IFRA Cat4: 0.04%',ifra:.04,rMin:.002,rMax:.04,indolic:false,sens:true,tenacity:45,impact:230},
{id:'caryophyllene_acetate',name:'Caryophyllene Acetate',fam:'Misc',note:'heart',desc:'Spicy-woody clove, slightly green',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:12,impact:100},
{id:'allyl_cyclohexyl_prop',name:'Allyl Cyclohexyl Propionate',fam:'Misc',note:'top',desc:'Pineapple, tropical slightly green',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:168,impact:130},
{id:'ethyl_safranate',name:'Ethyl Safranate',fam:'Misc',note:'top',desc:'Hay, saffron, tobacco diffusive',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:164,impact:100},
{id:'silvanone',name:'Silvanone',fam:'Misc',note:'base',desc:'Woody-musk, cedarwood facet',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:null,impact:null},
{id:'pineapple_base',name:'Pineapple Base',fam:'Misc',note:'top',desc:'Tropical pineapple accord, fruity',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:303.5,impact:100},
{id:'allyl_heptanoate',name:'Allyl Heptanoate',fam:'Misc',note:'top',desc:'Tropical pineapple, fruity-green',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:1,impact:null},
{id:'methyl_octine_carb',name:'Methyl Octine Carbonate',fam:'Misc',note:'top',desc:'Violet-green, powerful — Cat4: 0.002%',ifra:.002,rMin:.0002,rMax:.002,indolic:false,sens:true,tenacity:112,impact:1300},
{id:'dynascone',name:'Dynascone',fam:'Misc',note:'heart',desc:'Raspberry, rose, diffusive ketone',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:348,impact:250},
{id:'para_cresyl_acetate',name:'Para Cresyl Acetate',fam:'Misc',note:'base',desc:'Animalic honey narcotic — Cat4: 0.04%',ifra:.04,rMin:.005,rMax:.04,indolic:true,sens:true,tenacity:36,impact:360},
{id:'amberketal_ipm',name:'Amberketal IPM',fam:'Misc',note:'base',desc:'Amber accord, warm sweet resinous',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:100},
{id:'amber_core',name:'Amber Core',fam:'Misc',note:'base',desc:'Amber base, warm diffusive',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:168,impact:200},
{id:'hercolyn_d',name:'Hercolyn D',fam:'Misc',note:'base',desc:'Pine resin ester, balsamic soft',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:400,impact:25},
{id:'grisalva',name:'Grisalva',fam:'Misc',note:'base',desc:'Woody-amber, diffusive clean dry',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:48,impact:null},
{id:'manzanate',name:'Manzanate',fam:'Misc',note:'top',desc:'Apple, fresh green-fruity',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:90,impact:100},
{id:'safraleine',name:'Safraleine',fam:'Misc',note:'heart',desc:'Saffron, leather, smoky spicy',ifra:null,rMin:.1,rMax:2,indolic:false,sens:false,tenacity:168,impact:250},
{id:'cyclogalbanate',name:'Cyclogalbanate',fam:'Misc',note:'top',desc:'Galbanum-green, violet fresh',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:null,impact:null},
{id:'anise_star_eo',name:'Anise Star EO',fam:'Misc',note:'heart',desc:'Sweet anise, liquorice herbal',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:18,impact:125},
{id:'coriander_eo',name:'Coriander EO',fam:'Misc',note:'top',desc:'Spicy-woody citrusy, fresh herb',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:8,impact:145},
{id:'aniseed_eo',name:'Aniseed EO',fam:'Misc',note:'top',desc:'Anise, sweet liquorice',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:18,impact:120},
{id:'peppermint_eo',name:'Peppermint EO',fam:'Misc',note:'top',desc:'Fresh mint, cool mentholic',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:16,impact:400},
{id:'oregano_eo',name:'Oregano EO',fam:'Misc',note:'heart',desc:'Herbal, thyme-like, Mediterranean',ifra:null,rMin:.1,rMax:2,indolic:false,sens:false,tenacity:15,impact:140},
{id:'rosemary_eo',name:'Rosemary EO',fam:'Misc',note:'top',desc:'Fresh camphorous, herbal',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:4,impact:130},
{id:'camphor_eo',name:'Camphor EO',fam:'Misc',note:'top',desc:'Medicinal camphorous, cool',ifra:null,rMin:.1,rMax:2,indolic:false,sens:false,tenacity:4,impact:350},
{id:'ginger_eo',name:'Ginger EO',fam:'Misc',note:'top',desc:'Spicy-warm ginger, zesty fresh',ifra:null,rMin:.5,rMax:5,indolic:false,sens:false,tenacity:24,impact:200},
{id:'angelica_root_eo',name:'Angelica Root EO',fam:'Misc',note:'base',desc:'Earthy musky, slightly celery',ifra:null,rMin:.1,rMax:2,indolic:false,sens:false,tenacity:24,impact:150},
{id:'clove_bud_eo',name:'Clove Bud EO',fam:'Misc',note:'heart',desc:'Warm clove, eugenol-rich — Cat4: 0.5%',ifra:.5,rMin:.05,rMax:.5,indolic:false,sens:true,tenacity:188,impact:180},
{id:'peru_balsam_eo',name:'Peru Balsam EO',fam:'Misc',note:'base',desc:'Warm balsamic vanilla — IFRA Cat4: 0.4%',ifra:.4,rMin:.05,rMax:.4,indolic:false,sens:true,tenacity:400,impact:45},
{id:'safranal',name:'Safranal',fam:'Misc',note:'heart',desc:'Saffron, hay, slightly leathery',ifra:null,rMin:.05,rMax:1,indolic:false,sens:false,tenacity:7.13,impact:3.97},
{id:'eucalyptus_eo',name:'Eucalyptus EO',fam:'Misc',note:'top',desc:'Fresh medicinal, eucalyptol',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:4,impact:370},
{id:'sage_eo',name:'Sage EO',fam:'Misc',note:'top',desc:'Herbal, camphoraceous sage',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:12,impact:105},
{id:'black_pepper_eo',name:'Black Pepper EO',fam:'Misc',note:'top',desc:'Spicy, warm dry pepper',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:40,impact:150},
{id:'pink_peppercorn_eo',name:'Pink Peppercorn EO',fam:'Misc',note:'top',desc:'Fresh spicy, slightly fruity pepper',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:140,impact:100},
{id:'spearmint_eo',name:'Spearmint EO',fam:'Misc',note:'top',desc:'Minty sweet, gentler than peppermint',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:36,impact:230},
{id:'nutmeg_eo',name:'Nutmeg EO',fam:'Misc',note:'heart',desc:'Warm spice, woody slightly floral',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:48,impact:90},
{id:'white_thyme_eo',name:'White Thyme EO',fam:'Misc',note:'heart',desc:'Herbal thymol, medicinal',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:24,impact:570},
{id:'allspice_eo',name:'Allspice EO',fam:'Misc',note:'heart',desc:'Warm clove-cinnamon-nutmeg blend',ifra:null,rMin:.1,rMax:3,indolic:false,sens:false,tenacity:24,impact:130},
{id:'fennel_eo',name:'Fennel EO',fam:'Misc',note:'top',desc:'Anise-like herbal, slightly sweet',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:24,impact:180,cas:'8006-84-6',subFam:'Anisic',role:'Modifier',percepFactor:1.8,primaryFam:'Spice',secondaryFam:'Iceberg/Mint-Camphor',pwNote:'Fennel Sweet Essential Oil',dataSource:'PW'},
// PALETTE ADDITIONS
{id:'basil_eo',name:'Basil EO',fam:'Lav+Aromatic',note:'top',desc:'Fresh green herbal, anise-basil facets',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:4,impact:150},
{id:'calone',name:'Calone',fam:'Misc',note:'heart',desc:'Ozonic marine watermelon — use ultra-sparingly',ifra:null,rMin:.01,rMax:.5,indolic:false,sens:false,tenacity:600,impact:800,cas:'28940-11-6'},
{id:'cardamom_eo',name:'Cardamom EO',fam:'Misc',note:'top',desc:'Warm spicy, slightly sweet, slightly floral',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:12,impact:300},
{id:'cashmeran',name:'Cashmeran',fam:'Musks',note:'heart',desc:'Cashmere-like warm woody musk, spicy edge',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:200,impact:80,cas:'33704-61-9'},
{id:'cedramber_iff',name:'Cedramber IFF',fam:'Woods',note:'heart',desc:'Cedarwood-amber, dry woody diffusive',ifra:null,rMin:.5,rMax:8,indolic:false,sens:false,tenacity:125,impact:120},
{id:'cinnamon_bark_eo',name:'Cinnamon Bark EO',fam:'Misc',note:'heart',desc:'Warm cinnamon, sweet spicy — Cat4: 0.2%',ifra:.2,rMin:.01,rMax:.2,indolic:false,sens:true,tenacity:140,impact:150},
{id:'cis3_hexenol',name:'Cis-3-Hexenol',fam:'Misc',note:'top',desc:'Fresh-cut green grass, leafy, powerful',ifra:null,rMin:.05,rMax:2,indolic:false,sens:false,tenacity:4,impact:700,cas:'928-96-1'},
{id:'cis3_hexenyl_sal',name:'Cis-3-Hexenyl Salicylate',fam:'Aldehydes+Esters',note:'heart',desc:'Green leafy floral, fresh herbal',ifra:null,rMin:.1,rMax:5,indolic:false,sens:false,tenacity:216,impact:90,cas:'65405-77-8'},
{id:'cyclamen_aldehyde',name:'Cyclamen Aldehyde',fam:'Aldehydes+Esters',note:'top',desc:'Violet-lilac aldehydic, watery cyclamen',ifra:null,rMin:.05,rMax:2,indolic:false,sens:false,tenacity:72,impact:75,cas:'103-95-7'},
{id:'damascone_alpha',name:'Damascone Alpha',fam:'Rose',note:'heart',desc:'Rose fruity, apple-rose, highly diffusive',ifra:null,rMin:.05,rMax:2,indolic:false,sens:false,tenacity:60,impact:700,cas:'24720-09-0'},
{id:'damascone_beta',name:'Damascone Beta',fam:'Rose',note:'heart',desc:'Rose spicy woody, dried-rose character',ifra:null,rMin:.05,rMax:2,indolic:false,sens:false,tenacity:190,impact:450,cas:'23726-93-4'},
{id:'dihydro_myrcenol',name:'Dihydro Myrcenol',fam:'Misc',note:'top',desc:'Fresh citrus-lime, clean, pine facet',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:16,impact:100,cas:'18479-58-8'},
{id:'floralozone',name:'Floralozone',fam:'Misc',note:'heart',desc:'Ozonic floral, cyclohexyl, watery fresh',ifra:null,rMin:.1,rMax:5,indolic:false,sens:false,tenacity:80,impact:100,cas:'67634-15-5'},
{id:'frankincense_eo',name:'Frankincense EO',fam:'Naturals',note:'top',desc:'Incense, citrus-resinous, balsamic olibanum',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:188,impact:50},
{id:'geranyl_acetate',name:'Geranyl Acetate',fam:'Aldehydes+Esters',note:'top',desc:'Rose-geranium fruity, sweet waxy',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:24,impact:125,cas:'105-87-3'},
{id:'labdanum_abs',name:'Labdanum Abs',fam:'Naturals',note:'heart',desc:'Amber cistus, sweet animalic, complex',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:100,impact:200},
{id:'labdanum_eo',name:'Labdanum EO',fam:'Naturals',note:'top',desc:'Warm amber, cistus, slightly earthy resinous',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:400,impact:600},
{id:'labdanum_resinoid',name:'Labdanum Resinoid',fam:'Naturals',note:'heart',desc:'Amber cistus, sweet-earthy, balsamic',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:65,impact:400},
{id:'phenyl_ethyl_acetate',name:'Phenyl Ethyl Acetate',fam:'Aldehydes+Esters',note:'top',desc:'Rose-honey fruity, sweet floral',ifra:null,rMin:.2,rMax:5,indolic:false,sens:false,tenacity:16,impact:90,cas:'103-45-7'},
{id:'stemone',name:'Stemone',fam:'Misc',note:'top',desc:'Grapefruit-violet, citrus-iris, highly diffusive',ifra:null,rMin:.05,rMax:2,indolic:false,sens:false,tenacity:16,impact:1000},
{id:'cedarwood_virginian_eo',name:'Cedarwood Virginian EO',fam:'Woods',note:'top',desc:'Dry cedar, pencil-shavings, warm woody',ifra:null,rMin:.5,rMax:10,indolic:false,sens:false,tenacity:32,impact:90}
];
