// Auto-generated from JAG Lab Perfumery DB — 248 materials
import type { Material } from './types';

export const MATERIALS_DB: Material[] = [
  {
    id: 'aldc8',
    name: 'Ald C8',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 7,
    impact: 1000,
    description: 'Waxy citrus orange peel, powerful',
  },
  {
    id: 'aldc9',
    name: 'Ald C9',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 276,
    impact: 550,
    description: 'Rose waxy, floral, cucumber facet',
  },
  {
    id: 'aldc10',
    name: 'Ald C10',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 224,
    impact: 500,
    description: 'Citrus orange, waxy, classic Chanel note',
  },
  {
    id: 'aldc11',
    name: 'Ald C11',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 48,
    impact: 175,
    description: 'Fresh soapy floral, clean aldehydic',
  },
  {
    id: 'aldc12_lauric',
    name: 'Ald C12 Lauric',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 380,
    impact: 700,
    description: 'Waxy soapy, slightly floral',
  },
  {
    id: 'aldc12_mna',
    name: 'Ald C12 MNA',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 388,
    impact: 700,
    description: 'Clean floral, muguet, powdery',
  },
  {
    id: 'aldc14_peach',
    name: 'Ald C14 Peach',
    family: 'Aldehydes+Esters',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 340,
    impact: 360,
    description: 'Peach apricot, slightly coconut',
  },
  {
    id: 'aldc19',
    name: 'Ald C19',
    family: 'Aldehydes+Esters',
    role: 'Heart',
    note: 'Heart',
    description: 'Fresh aldehydic, iris-like, powdery',
  },
  {
    id: 'allyl_amyl_glycolate',
    name: 'Allyl Amyl Glycolate',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 84,
    impact: 170,
    ifraLimit: 0.002,
    description: 'Pineapple-green, powerful — Cat4: 0.002%',
  },
  {
    id: 'allyl_caproate_c6',
    name: 'Allyl Caproate C6',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    cas: '123-68-2',
    tenacityHours: 1,
    impact: 250,
    description: 'Pineapple, tropical, fruity',
  },
  {
    id: 'benzyl_acetate',
    name: 'Benzyl Acetate',
    family: 'Aldehydes+Esters',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 4,
    impact: 120,
    ifraLimit: 7,
    description: 'Jasmine, floral, fruity sweet — Cat4: 7%',
  },
  {
    id: 'benzyl_benzoate',
    name: 'Benzyl Benzoate',
    family: 'Aldehydes+Esters',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 322,
    impact: 18,
    description: 'Faint balsamic, fixative solvent',
  },
  {
    id: 'benzyl_salicylate',
    name: 'Benzyl Salicylate',
    family: 'Aldehydes+Esters',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 384,
    impact: 30,
    ifraLimit: 2,
    description: 'Soft balsamic floral fixer — Cat4: 2%',
  },
  {
    id: 'iso_amyl_salicylate',
    name: 'Iso Amyl Salicylate',
    family: 'Aldehydes+Esters',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 124,
    impact: 110,
    ifraLimit: 1,
    description: 'Clover sweet faint floral — Cat4: 1%',
  },
  {
    id: 'habanolide',
    name: 'Habanolide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 100,
    description: 'Macrocyclic musk, clean, smooth',
  },
  {
    id: 'galaxolide_undil',
    name: 'Galaxolide Undil',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 60,
    ifraLimit: 5.3,
    description: 'Powdery clean woody musk — Cat4: 5.3%',
  },
  {
    id: 'timbersilk',
    name: 'Timbersilk',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 172,
    description: 'Woody clean silky musk',
  },
  {
    id: 'velvione',
    name: 'Velvione',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 720,
    impact: 25,
    description: 'Macrocyclic, velvety warm musk',
  },
  {
    id: 'romandolide',
    name: 'Romandolide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 100,
    description: 'Macrocyclic, creamy soft musk',
  },
  {
    id: 'timberol',
    name: 'Timberol',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 10,
    impact: 100,
    description: 'Sandalwood-musk, creamy woody',
  },
  {
    id: 'ethylene_brassylate',
    name: 'Ethylene Brassylate',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 280,
    impact: 40,
    description: 'Macrocyclic, sweet clean musk',
  },
  {
    id: 'muscenone_delta',
    name: 'Muscenone Delta',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    description: 'Macrocyclic, musky subtle skin',
  },
  {
    id: 'ambrofix_powder',
    name: 'Ambrofix Powder',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 720,
    impact: 200,
    description: 'Ambergris, woody warm diffusive',
  },
  {
    id: 'helvetolide',
    name: 'Helvetolide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 100,
    description: 'Fruity musk, pear-like, clean',
  },
  {
    id: 'musk_ketone',
    name: 'Musk Ketone',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 35,
    ifraLimit: 0.07,
    description: 'Nitro musk, powdery (restricted) — Cat4: 0.07%',
  },
  {
    id: 'exaltolide_total',
    name: 'Exaltolide Total',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 25,
    description: 'Macrocyclic, classic exaltolide',
  },
  {
    id: 'ambrettolide',
    name: 'Ambrettolide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 172,
    impact: 30,
    description: 'Macrocyclic, natural-seeming musk',
  },
  {
    id: 'tonalide',
    name: 'Tonalide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 20,
    ifraLimit: 0.03,
    description: 'Polycyclic musk (restricted) — Cat4: 0.03%',
  },
  {
    id: 'exaltolide',
    name: 'Exaltolide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 25,
    description: 'Macrocyclic musk, warm smooth',
  },
  {
    id: 'edenolide',
    name: 'Edenolide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 148,
    impact: 100,
    description: 'Macrocyclic, fruity creamy musk',
  },
  {
    id: 'ambrocenide',
    name: 'Ambrocenide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 100,
    description: 'Macrocyclic, woody smoky musk',
  },
  {
    id: 'ambrettolide_iff',
    name: 'Ambrettolide IFF',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 172,
    impact: 30,
    description: 'IFF version, macrocyclic natural',
  },
  {
    id: 'ambrox_super',
    name: 'Ambrox Super',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 750,
    impact: 500,
    description: 'Ambergris, warm woody diffusive',
  },
  {
    id: 'globanone_50_dpg',
    name: 'Globanone 50 DPG',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 260,
    description: 'Macrocyclic musk 50% in DPG',
  },
  {
    id: 'globalide',
    name: 'Globalide',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 350,
    description: 'Macrocyclic, smooth clean musk',
  },
  {
    id: 'sbq',
    name: 'SBQ',
    family: 'Musks',
    role: 'Fixative',
    note: 'Base',
    description: 'Macrocyclic musk, clean diffusive',
  },
  {
    id: 'vetiveryl_acetate',
    name: 'Vetiveryl Acetate',
    family: 'Patchouli+Vetiver',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 360,
    impact: 80,
    description: 'Vetiver ester, woody smoky dry',
  },
  {
    id: 'patchouli_aura',
    name: 'Patchouli Aura Cacia',
    family: 'Patchouli+Vetiver',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 98,
    description: 'Natural patchouli, earthy camphor',
  },
  {
    id: 'patchouli_light',
    name: 'Patchouli Light EO',
    family: 'Patchouli+Vetiver',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 100,
    description: 'Light patchouli, less earthy, softer',
  },
  {
    id: 'vetiver_eo',
    name: 'Vetiver EO',
    family: 'Patchouli+Vetiver',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 105,
    description: 'Smoky woody earthy, clean drydown',
  },
  {
    id: 'cypriol_eo',
    name: 'Cypriol EO',
    family: 'Patchouli+Vetiver',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 2.5,
    impact: 110,
    description: 'Smoky, woody, oud-like, dry',
  },
  {
    id: 'patchouli_dark',
    name: 'Patchouli Dark',
    family: 'Patchouli+Vetiver',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 98,
    description: 'Dark patchouli, heavy earthy deep',
  },
  {
    id: 'lemon',
    name: 'Lemon',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 130,
    description: 'Fresh bright lemon, ~5% citral',
  },
  {
    id: 'sweet_orange',
    name: 'Sweet Orange',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 110,
    description: 'Sweet juicy orange, clean fresh',
  },
  {
    id: 'citral',
    name: 'Citral',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 12,
    impact: 270,
    ifraLimit: 1,
    description: 'Pure lemon-lime, 100% citral — Cat4: 1.0%',
  },
  {
    id: 'methyl_pamplemousse',
    name: 'Methyl Pamplemousse',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 3,
    impact: 0,
    description: 'Synthetic grapefruit, fresh rosy',
  },
  {
    id: 'bergamot_fcr',
    name: 'Bergamot FCR',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 8,
    impact: 100,
    description: 'Bergamot furocoumarin-free, no phototoxic risk',
  },
  {
    id: 'blood_orange',
    name: 'Blood Orange',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 100,
    description: 'Sweet orange with berry facet',
  },
  {
    id: 'petitgrain',
    name: 'Petitgrain',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 28,
    impact: 110,
    description: 'Woody citrus, herbal green-floral',
  },
  {
    id: 'grapefruit',
    name: 'Grapefruit',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 16,
    impact: 125,
    description: 'Tart fresh, slightly bitter grapefruit',
  },
  {
    id: 'lime_eo',
    name: 'Lime EO',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 20,
    impact: 300,
    description: 'Sharp citrus-lime, fresh, ~6% citral',
  },
  {
    id: 'lemongrass',
    name: 'Lemongrass',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 11,
    impact: 150,
    ifraLimit: 0.7,
    description: 'Lemony-grassy, ~70% citral — Cat4: 0.7%',
  },
  {
    id: 'mandarin',
    name: 'Mandarin',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 90,
    description: 'Sweet tangy mandarin, diffusive',
  },
  {
    id: 'citronellal',
    name: 'Citronellal',
    family: 'Citrus',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 16,
    impact: 380,
    ifraLimit: 0.6,
    description: 'Rosy-citronella — IFRA Cat4: 0.6%',
  },
  {
    id: 'clary_sage_eo',
    name: 'Clary Sage EO',
    family: 'Lav+Aromatic',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 48,
    impact: 105,
    description: 'Herbaceous, slightly sweet amber facet',
  },
  {
    id: 'linalool_natural',
    name: 'Linalool Natural',
    family: 'Lav+Aromatic',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 12,
    impact: 100,
    ifraLimit: 24,
    description: 'Rose-woody soft floral, EU allergen',
  },
  {
    id: 'cedar_leaf_eo',
    name: 'Cedar Leaf EO',
    family: 'Lav+Aromatic',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 30,
    impact: 220,
    description: 'Fresh camphorous, green woody',
  },
  {
    id: 'lavender_eo',
    name: 'Lavender EO',
    family: 'Lav+Aromatic',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 27,
    impact: 110,
    description: 'Classic lavender, floral herbal fresh',
  },
  {
    id: 'lavandin_eo',
    name: 'Lavandin EO',
    family: 'Lav+Aromatic',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 4,
    impact: 110,
    description: 'Camphoraceous lavender, slightly harsh',
  },
  {
    id: 'linalyl_acetate',
    name: 'Linalyl Acetate',
    family: 'Lav+Aromatic',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 20,
    impact: 110,
    description: 'Fresh bergamot-floral, key lavender ester',
  },
  {
    id: 'red_thyme_eo',
    name: 'Red Thyme EO',
    family: 'Lav+Aromatic',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 35,
    impact: 570,
    ifraLimit: 0.5,
    description: 'Herbal spicy-phenolic, powerful — Cat4: 0.5%',
  },
  {
    id: 'menthol_crystal',
    name: 'Menthol Crystal',
    family: 'Lav+Aromatic',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 32,
    impact: 120,
    description: 'Intensely cooling, peppermint minty',
  },
  {
    id: 'lavender_4042',
    name: 'Lavender 40/42',
    family: 'Lav+Aromatic',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 27,
    impact: 110,
    description: 'Standardised lavender, consistent quality',
  },
  {
    id: 'ethyl_linalool',
    name: 'Ethyl Linalool',
    family: 'Lav+Aromatic',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 30,
    impact: 100,
    description: 'Fresh slightly green linalool variant',
  },
  {
    id: 'linalool_coeur',
    name: 'Linalool Coeur',
    family: 'Lav+Aromatic',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 12,
    impact: 100,
    description: 'Rosewood-woody, clean floral linalool',
  },
  {
    id: 'heliotropin_x24',
    name: 'Heliotropin X24',
    family: 'Jasmine+Hedione',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 400,
    impact: 90,
    description: 'Powdery heliotrope, almond-cherry-vanilla',
  },
  {
    id: 'hedione',
    name: 'Hedione',
    family: 'Jasmine+Hedione',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 168,
    impact: 65,
    description: 'Diffusive jasmine, fresh clean, revolutionary',
  },
  {
    id: 'hedione_hc',
    name: 'Hedione HC',
    family: 'Jasmine+Hedione',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 720,
    impact: 65,
    description: 'High-cis hedione, stronger more floral',
  },
  {
    id: 'helional',
    name: 'Helional',
    family: 'Jasmine+Hedione',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 60,
    impact: 80,
    description: 'Lily-of-the-valley, fresh marine floral',
  },
  {
    id: 'rose_givco217',
    name: 'Rose Givco 217',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    description: 'Rose base accord, full-bodied warm',
  },
  {
    id: 'rose_oxide_hc',
    name: 'Rose Oxide HC',
    family: 'Florals+Muguet',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 8,
    impact: 700,
    description: 'Key rose oxide, geranium-rosy, powerful',
  },
  {
    id: 'melonal',
    name: 'Melonal',
    family: 'Florals+Muguet',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 160,
    impact: 700,
    description: 'Watermelon, cucumber, fresh green',
  },
  {
    id: 'rose_absolute',
    name: 'Rose Absolute',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 24,
    impact: 250,
    description: 'Natural rose, rich waxy complex',
  },
  {
    id: 'sambac_floraline',
    name: 'Sambac Floraline',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 45,
    impact: 145,
    description: 'Jasmine sambac accord, creamy indolic',
  },
  {
    id: 'aurantiol',
    name: 'Aurantiol',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 300,
    impact: 44,
    ifraLimit: 0.2,
    description: 'Orange blossom, methyl anthranilate-based — Cat4: ~0.2%',
  },
  {
    id: 'jasmine_floraline',
    name: 'Jasmine Floraline',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 45,
    impact: 170,
    description: 'Jasmine accord, clean diffusive floral',
  },
  {
    id: 'florol',
    name: 'Florol',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 24,
    impact: 100,
    description: 'Lily-of-the-valley, clean watery',
  },
  {
    id: 'magnolia_floraline',
    name: 'Magnolia Floraline',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    description: 'Magnolia accord, citrusy-floral soft',
  },
  {
    id: 'hydroxycitronellal',
    name: 'Hydroxycitronellal',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 192,
    impact: 25,
    ifraLimit: 1,
    description: 'Muguet-linden, sweet floral — Cat4: 1.0%',
  },
  {
    id: 'lilyflore',
    name: 'Lilyflore',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 720,
    description: 'Lily, clean slightly green floral',
  },
  {
    id: 'triplamour',
    name: 'Triplamour',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    description: 'Floral slightly powdery, modern',
  },
  {
    id: 'tuberose_floraline75',
    name: 'Tuberose Floraline 75',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 36,
    impact: 250,
    description: 'Rich tuberose accord, creamy dense',
  },
  {
    id: 'neroli_eo',
    name: 'Neroli EO',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 120,
    impact: 120,
    description: 'Orange blossom, fresh floral bitter',
  },
  {
    id: 'nerolidol',
    name: 'Nerolidol',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 100,
    impact: 38,
    description: 'Rose-apple-green, woody facet, fresh',
  },
  {
    id: 'hexyl_cinnamic_ald',
    name: 'Hexyl Cinnamic Aldehyde',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 400,
    impact: 100,
    ifraLimit: 5.6,
    description: 'Jasmine, warm floral, HCA — Cat4: 5.6%',
  },
  {
    id: 'nympheal',
    name: 'Nympheal',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 700,
    impact: 100,
    description: 'Lily-of-the-valley, clean aquatic-floral',
  },
  {
    id: 'mayol',
    name: 'Mayol',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 24,
    impact: 100,
    description: 'Muguet, clean slightly rosy lily',
  },
  {
    id: 'coranol',
    name: 'Coranol',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 20,
    description: 'Rosy-muguet, clean fresh floral',
  },
  {
    id: 'bourgeonal',
    name: 'Bourgeonal',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 100,
    impact: 80,
    ifraLimit: 0.01,
    description: 'Powerful muguet (restricted) — Cat4: 0.01%',
  },
  {
    id: 'methyl_diantilis',
    name: 'Methyl Diantilis',
    family: 'Florals+Muguet',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 400,
    impact: 100,
    description: 'Carnation, clove-spicy floral',
  },
  {
    id: 'orris_root_abs',
    name: 'Orris Root Abs',
    family: 'Iris+Ionones',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 296,
    impact: 40,
    description: 'Orris, powdery violet carroty',
  },
  {
    id: 'ionone_beta',
    name: 'Ionone Beta',
    family: 'Iris+Ionones',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 48,
    impact: 120,
    description: 'Woody violet, iris, slightly sweet',
  },
  {
    id: 'methyl_ionone_gamma',
    name: 'Methyl Ionone Gamma EQ',
    family: 'Iris+Ionones',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 124,
    impact: 90,
    description: 'Soft violet-iris, powdery warm',
  },
  {
    id: 'methyl_ionone_alpha',
    name: 'Methyl Ionone Alpha',
    family: 'Iris+Ionones',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 124,
    impact: 90,
    description: 'Violet-iris, woody Orris character',
  },
  {
    id: 'ionone_alpha',
    name: 'Ionone Alpha',
    family: 'Iris+Ionones',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 48,
    impact: 100,
    description: 'Floral violet, sweet fresh',
  },
  {
    id: 'dihydro_ionone_beta',
    name: 'Dihydro Ionone Beta',
    family: 'Iris+Ionones',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 9,
    impact: 220,
    description: 'Woody iris, slightly smoky',
  },
  {
    id: 'isoraldeine_95',
    name: 'Isoraldeine 95',
    family: 'Iris+Ionones',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 124,
    description: 'Powerful iris-violet, metallic facet',
  },
  {
    id: 'orris_base_givco',
    name: 'Orris Base Givco',
    family: 'Iris+Ionones',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 28,
    impact: 40,
    description: 'Givco orris accord, powdery floral',
  },
  {
    id: 'herbanate',
    name: 'Herbanate',
    family: 'Musk Specialties',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 72,
    description: 'Woody-green musk, spirene-like character',
  },
  {
    id: 'norlimbanol',
    name: 'Norlimbanol',
    family: 'Musk Specialties',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 300,
    impact: 1000,
    description: 'Sandalwood-musk, powerful woody',
  },
  {
    id: 'ambrette_abs',
    name: 'Ambrette Abs India',
    family: 'Musk Specialties',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 332,
    impact: 94,
    description: 'Natural musk seed, musky wine-like',
  },
  {
    id: 'anethole',
    name: 'Anethole',
    family: 'Gourmand',
    role: 'Heart',
    note: 'Heart',
    description: 'Anise, sweet, liquorice, herbal-sweet',
  },
  {
    id: 'ethyl_vanillin',
    name: 'Ethyl Vanillin',
    family: 'Gourmand',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 600,
    description: 'Vanilla 3× stronger than vanillin',
  },
  {
    id: 'fructone',
    name: 'Fructone',
    family: 'Gourmand',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 72,
    impact: 80,
    description: 'Fruity, apple, pineapple tropical',
  },
  {
    id: 'coumarin',
    name: 'Coumarin',
    family: 'Gourmand',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 364,
    impact: 120,
    ifraLimit: 2.18,
    description: 'Hay, tonka, sweet — IFRA Cat4: 2.18%',
  },
  {
    id: 'tonka_abs',
    name: 'Tonka Bean Abs 20 DPG',
    family: 'Gourmand',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 364,
    impact: 260,
    description: 'Tonka, vanilla-coumarin, sweet almond',
  },
  {
    id: 'ethyl_maltol',
    name: 'Ethyl Maltol',
    family: 'Gourmand',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 360,
    impact: 2500,
    description: 'Cotton candy, caramel, sweet fruity',
  },
  {
    id: 'raspberry_ketone',
    name: 'Raspberry Ketone',
    family: 'Gourmand',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 336,
    impact: 70,
    description: 'Raspberry, fruity, rosy facet',
  },
  {
    id: 'vanillin',
    name: 'Vanillin',
    family: 'Gourmand',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 60,
    description: 'Classic vanilla, sweet warm balsamic',
  },
  {
    id: 'vanillin_sig',
    name: 'Vanillin Sig',
    family: 'Gourmand',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 60,
    description: 'Signature vanillin, pure high quality',
  },
  {
    id: 'vanillin_isobutyrate',
    name: 'Vanillin Iso Butyrate',
    family: 'Gourmand',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    description: 'Vanilla ester, creamy slightly floral',
  },
  {
    id: 'yara_yara',
    name: 'Yara Yara',
    family: 'Gourmand',
    role: 'Heart',
    note: 'Heart',
    description: 'Beta-naphthyl methyl ether, neroli-cherry',
  },
  {
    id: 'tonquitone',
    name: 'Tonquitone',
    family: 'Gourmand',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 300,
    description: 'Muguet-tonka, sweet coumarinic floral',
  },
  {
    id: 'castoreum_givco',
    name: 'Castoreum Givco 116',
    family: 'Animalics',
    role: 'Fixative',
    note: 'Base',
    description: 'Leather-animalic castoreum type',
  },
  {
    id: 'indole',
    name: 'Indole',
    family: 'Animalics',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 400,
    impact: 700,
    ifraLimit: 0.1,
    description: 'Jasmine-animalic-fecal — IFRA Cat4: 0.1%',
  },
  {
    id: 'civette_givco',
    name: 'Civette Givco 208',
    family: 'Animalics',
    role: 'Fixative',
    note: 'Base',
    description: 'Civet accord, animalic musky-fecal',
  },
  {
    id: 'creosol',
    name: 'Creosol',
    family: 'Animalics',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 132,
    description: 'Smoky tarry phenolic, leather character',
  },
  {
    id: 'veramoss',
    name: 'Veramoss',
    family: 'Tobacco',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 360,
    description: 'Oakmoss substitute, mossy green',
  },
  {
    id: 'coffee_co2',
    name: 'Coffee CO2',
    family: 'Tobacco',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 400,
    impact: 150,
    description: 'Rich roasted coffee, dark bittersweet',
  },
  {
    id: 'oakmoss_abs',
    name: 'Oakmoss Abs',
    family: 'Tobacco',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 125,
    ifraLimit: 0.1,
    description: 'Classic chypre material — IFRA Cat4: 0.1%',
  },
  {
    id: 'tobacco_abs',
    name: 'Tobacco Abs',
    family: 'Tobacco',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 36,
    impact: 400,
    description: 'Natural tobacco, smoky dried herb',
  },
  {
    id: 'nerol_90',
    name: 'Nerol 90',
    family: 'Rose',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 24,
    impact: 100,
    description: 'Rosy fresh, neroli facet geranium',
  },
  {
    id: 'geranium_eo',
    name: 'Geranium EO',
    family: 'Rose',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 8,
    impact: 170,
    description: 'Rose-green, herbal fresh complex',
  },
  {
    id: 'citronellol',
    name: 'Citronellol',
    family: 'Rose',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 48,
    impact: 100,
    ifraLimit: 5.3,
    description: 'Rosy fresh sweet — IFRA Cat4: 5.3%',
  },
  {
    id: 'phenyl_ethyl_alc',
    name: 'Phenyl Ethyl Alcohol',
    family: 'Rose',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 32,
    impact: 60,
    ifraLimit: 6.3,
    description: 'Core rose alcohol — IFRA Cat4: 6.3%',
  },
  {
    id: 'geraniol_extra',
    name: 'Geraniol Extra',
    family: 'Rose',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 60,
    impact: 100,
    ifraLimit: 2.2,
    description: 'Rose-geranium ~98% geraniol — Cat4: 2.2%',
  },
  {
    id: 'phenoxanol',
    name: 'Phenoxanol',
    family: 'Rose',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 400,
    impact: 100,
    description: 'Rosy, muguet-facet, clean smooth',
  },
  {
    id: 'honeysuckle_abs',
    name: 'Honeysuckle Abs',
    family: 'Naturals',
    role: 'Heart',
    note: 'Heart',
    description: 'Natural honeysuckle, sweet diffusive',
  },
  {
    id: 'ylang_ylang_eo',
    name: 'Ylang Ylang 1+3 EO',
    family: 'Naturals',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 140,
    impact: 120,
    ifraLimit: 0.6,
    description: 'Heavy floral, indolic — IFRA Cat4: 0.6%',
  },
  {
    id: 'javanol',
    name: 'Javanol',
    family: 'Naturals',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 250,
    description: 'Sandalwood, creamy milky precious',
  },
  {
    id: 'tagetes_abs',
    name: 'Tagetes Abs',
    family: 'Naturals',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 25,
    impact: 100,
    ifraLimit: 0.01,
    description: 'Marigold green-fruity — IFRA Cat4: 0.01%',
  },
  {
    id: 'green_tea_abs',
    name: 'Green Tea Abs',
    family: 'Naturals',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 0,
    impact: 150,
    description: 'Fresh green tea, vegetal clean',
  },
  {
    id: 'rosewood_eo',
    name: 'Rosewood EO',
    family: 'Naturals',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 12,
    impact: 100,
    description: 'Floral rosewood, linalool-rich smooth',
  },
  {
    id: 'elemi_eo',
    name: 'Elemi EO+Resinoid 50BB',
    family: 'Naturals',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 50,
    impact: 120,
    description: 'Citrus-resinous, spicy, frankincense',
  },
  {
    id: 'birch_tar',
    name: 'Birch Tar Rect',
    family: 'Leather',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 1200,
    ifraLimit: 1,
    description: 'Smoky leather, tarry medicinal — Cat4: 1%',
  },
  {
    id: 'isobutyl_quinoline',
    name: 'Isobutyl Quinoline',
    family: 'Leather',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 50,
    impact: 450,
    description: 'Leather, quinoline, smoky dry',
  },
  {
    id: 'eugenol',
    name: 'Eugenol USP',
    family: 'Leather',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 52,
    impact: 175,
    ifraLimit: 0.5,
    description: 'Clove spice, warm — IFRA Cat4: 0.5%',
  },
  {
    id: 'suederal',
    name: 'Suederal LT',
    family: 'Leather',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 168,
    impact: 250,
    description: 'Suede leather, smooth modern',
  },
  {
    id: 'guaiacol',
    name: 'Guaiacol',
    family: 'Leather',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 280,
    impact: 1250,
    description: 'Smoky, phenolic, medicinal-leather',
  },
  {
    id: 'sandalwood_australia',
    name: 'Sandalwood Australia EO',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 999,
    impact: 70,
    description: 'Creamy sandalwood, buttery precious',
  },
  {
    id: 'agarwood_black_rco',
    name: 'Agarwood Black RCO',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 480,
    impact: 120,
    description: 'Oud, smoky dark animalic-woody',
  },
  {
    id: 'cedarwood_atlas',
    name: 'Cedarwood Atlas EO',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 192,
    description: 'Warm cedar, slightly sweet classic',
  },
  {
    id: 'iso_e_super',
    name: 'Iso E Super',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 280,
    impact: 40,
    description: 'Cedar-cyclo, skin-close, pheromonic',
  },
  {
    id: 'olibanol',
    name: 'Olibanol',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    description: 'Frankincense/olibanum, balsamic resin',
  },
  {
    id: 'guaiac_wood',
    name: 'Guaiac Wood',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 60,
    impact: 1250,
    description: 'Smoky, rosy-woody, tea-like',
  },
  {
    id: 'olibanum_abs',
    name: 'Olibanum Abs',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    description: 'Natural frankincense absolute',
  },
  {
    id: 'sandalore',
    name: 'Sandalore',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    description: 'Synthetic sandalwood, creamy woody',
  },
  {
    id: 'polysantol',
    name: 'Polysantol',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 336,
    impact: 100,
    description: 'Sandalwood, milky soft creamy',
  },
  {
    id: 'hindinol',
    name: 'Hindinol',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 100,
    description: 'Sandalwood, powerful lasting',
  },
  {
    id: 'oud_synth',
    name: 'Oud Synth 184007',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 480,
    impact: 100,
    description: 'Synthetic oud, smoky dark-woody',
  },
  {
    id: 'bacdanol',
    name: 'Bacdanol',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 336,
    impact: 80,
    description: 'Sandalwood type, clean smooth',
  },
  {
    id: 'clearwood',
    name: 'Clearwood',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 168,
    description: 'Vetiver-patchouli-woody, clean',
  },
  {
    id: 'vertofix_coeur',
    name: 'Vertofix Coeur',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 70,
    description: 'Woody-cedar, smooth slightly spicy',
  },
  {
    id: 'ebanol',
    name: 'Ebanol',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 125,
    description: 'Sandalwood, slightly green creamy',
  },
  {
    id: 'cedryl_acetate',
    name: 'Cedryl Acetate Liquid',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 60,
    description: 'Cedar ester, warm smooth woody',
  },
  {
    id: 'kephalis',
    name: 'Kephalis',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 80,
    impact: 80,
    description: 'Fir needle-cedar, dry cool conifer',
  },
  {
    id: 'sandela_85',
    name: 'Sandela 85',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 20,
    description: 'Sandalwood note by Givaudan',
  },
  {
    id: 'amyris_eo',
    name: 'Amyris EO',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 2000,
    impact: 120,
    description: 'Sandalwood substitute, woody creamy',
  },
  {
    id: 'fir_needle_eo',
    name: 'Fir Needle EO',
    family: 'Woods',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 24,
    impact: 125,
    description: 'Fresh conifer, green clean',
  },
  {
    id: 'myrrh_co2',
    name: 'Myrrh CO2',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 60,
    description: 'Myrrh resin, balsamic spicy-woody',
  },
  {
    id: 'juniper_eo',
    name: 'Juniper EO',
    family: 'Woods',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 24,
    impact: 200,
    description: 'Fresh gin-like, piney clean',
  },
  {
    id: 'cypress_eo',
    name: 'Cypress EO',
    family: 'Woods',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 44,
    impact: 110,
    description: 'Fresh conifer, slightly herbal',
  },
  {
    id: 'fir_balsam_eo',
    name: 'Fir Balsam EO',
    family: 'Woods',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 12,
    impact: 90,
    description: 'Balsamic fir, warm resinous',
  },
  {
    id: 'cinnamyl_alcohol',
    name: 'Cinnamyl Alcohol',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 371,
    impact: 80,
    ifraLimit: 0.6,
    description: 'Hyacinth-cinnamon — IFRA Cat4: 0.6%',
  },
  {
    id: 'ethyl_butyrate',
    name: 'Ethyl Butyrate',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 460,
    description: 'Fruity, apple, pineapple tropical',
  },
  {
    id: 'cinnamaldehyde',
    name: 'Cinnamaldehyde',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 75,
    impact: 130,
    ifraLimit: 0.07,
    description: 'Cinnamon spice — IFRA Cat4: 0.07%',
  },
  {
    id: 'damascenone',
    name: 'Damascenone',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 200,
    impact: 500,
    description: 'Rose-apple ketone, extreme impact',
  },
  {
    id: 'tec',
    name: 'TEC (Triethyl Citrate)',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    description: 'Plasticizer/solvent, odourless carrier',
  },
  {
    id: 'methyl_anthranilate',
    name: 'Methyl Anthranilate',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 88,
    impact: 420,
    ifraLimit: 0.1,
    description: 'Grape, orange flower — IFRA Cat4: 0.1%',
  },
  {
    id: 'bht',
    name: 'BHT',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 24,
    impact: 1,
    description: 'Antioxidant preservative, near-odourless',
  },
  {
    id: 'cassis_345b',
    name: 'Cassis 345B',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 350,
    description: 'Blackcurrant, green, sulphurous facet',
  },
  {
    id: 'gamma_undecalactone',
    name: 'Gamma Undecalactone',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 340,
    impact: 180,
    description: 'Peach, coconut, fruity creamy',
  },
  {
    id: 'damascone_abd',
    name: 'Damascone ABD',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    description: 'Rose-apple-fruity ketone, powerful',
  },
  {
    id: 'galbanum_eo',
    name: 'Galbanum EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 70,
    impact: 600,
    description: 'Green, pine, resinous sharp',
  },
  {
    id: 'ambrinol',
    name: 'Ambrinol',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 96,
    description: 'Ambergris, woody warm diffusive',
  },
  {
    id: 'benzyl_alcohol',
    name: 'Benzyl Alcohol',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 35,
    impact: 5,
    description: 'Faint almond-rose, solvent carrier',
  },
  {
    id: 'carrot_seed_eo',
    name: 'Carrot Seed EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 100,
    impact: 185,
    description: 'Warm earthy carrot, slightly woody',
  },
  {
    id: 'triplal',
    name: 'Triplal',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 24,
    impact: 800,
    description: 'Aldehydic citrus-herbal, clean fresh',
  },
  {
    id: 'galbanum_resinoid',
    name: 'Galbanum Resinoid',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 88,
    description: 'Green-balsamic, resinous deep',
  },
  {
    id: 'cis_jasmone_lactone',
    name: 'Cis Jasmone Lactone',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 60,
    description: 'Jasmine, clean floral fruity facet',
  },
  {
    id: 'dpg',
    name: 'DPG',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 7,
    impact: 3,
    description: 'Dipropylene glycol carrier, odourless',
  },
  {
    id: 'phenyl_acetaldehyde',
    name: 'Phenyl Acetaldehyde',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 9.1,
    impact: 42.7,
    ifraLimit: 0.1,
    description: 'Hyacinth honey animalic — Cat4: 0.1%',
  },
  {
    id: 'verdox_hc',
    name: 'Verdox HC',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 30,
    impact: 160,
    description: 'Cedar-woody, fresh green',
  },
  {
    id: 'styrax_storax',
    name: 'Styrax/Storax',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 100,
    description: 'Balsamic smoky, styrene-resin',
  },
  {
    id: 'anisic_aldehyde',
    name: 'Anisic Aldehyde',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 50,
    impact: 130,
    ifraLimit: 0.1,
    description: 'Anise hawthorn sweet — Cat4: 0.1%',
  },
  {
    id: 'dimethyl_anthranilate',
    name: 'Dimethyl Anthranilate',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 50,
    impact: 90,
    description: 'Grape floral, gentler than methyl anth.',
  },
  {
    id: 'iso_damascone',
    name: 'Iso Damascone',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    description: 'Rose-plum-apple, powerful ketone',
  },
  {
    id: 'florhydral',
    name: 'Florhydral',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 144,
    description: 'Cyclamen, fresh aquatic-floral',
  },
  {
    id: 'styrallyl_acetate',
    name: 'Styrallyl Acetate',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 8,
    impact: 350,
    description: 'Gardenia, citrus-floral green',
  },
  {
    id: 'cassia_eo',
    name: 'Cassia EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 45,
    impact: 230,
    ifraLimit: 0.04,
    description: 'Chinese cinnamon — IFRA Cat4: 0.04%',
  },
  {
    id: 'caryophyllene_acetate',
    name: 'Caryophyllene Acetate',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 12,
    impact: 100,
    description: 'Spicy-woody clove, slightly green',
  },
  {
    id: 'allyl_cyclohexyl_prop',
    name: 'Allyl Cyclohexyl Propionate',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 168,
    impact: 130,
    description: 'Pineapple, tropical slightly green',
  },
  {
    id: 'ethyl_safranate',
    name: 'Ethyl Safranate',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 164,
    impact: 100,
    description: 'Hay, saffron, tobacco diffusive',
  },
  {
    id: 'silvanone',
    name: 'Silvanone',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    description: 'Woody-musk, cedarwood facet',
  },
  {
    id: 'pineapple_base',
    name: 'Pineapple Base',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 303.5,
    impact: 100,
    description: 'Tropical pineapple accord, fruity',
  },
  {
    id: 'allyl_heptanoate',
    name: 'Allyl Heptanoate',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 1,
    description: 'Tropical pineapple, fruity-green',
  },
  {
    id: 'methyl_octine_carb',
    name: 'Methyl Octine Carbonate',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 112,
    impact: 1300,
    ifraLimit: 0.002,
    description: 'Violet-green, powerful — Cat4: 0.002%',
  },
  {
    id: 'dynascone',
    name: 'Dynascone',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 348,
    impact: 250,
    description: 'Raspberry, rose, diffusive ketone',
  },
  {
    id: 'para_cresyl_acetate',
    name: 'Para Cresyl Acetate',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 36,
    impact: 360,
    ifraLimit: 0.04,
    description: 'Animalic honey narcotic — Cat4: 0.04%',
  },
  {
    id: 'amberketal_ipm',
    name: 'Amberketal IPM',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 100,
    description: 'Amber accord, warm sweet resinous',
  },
  {
    id: 'amber_core',
    name: 'Amber Core',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 168,
    impact: 200,
    description: 'Amber base, warm diffusive',
  },
  {
    id: 'hercolyn_d',
    name: 'Hercolyn D',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 25,
    description: 'Pine resin ester, balsamic soft',
  },
  {
    id: 'grisalva',
    name: 'Grisalva',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 48,
    description: 'Woody-amber, diffusive clean dry',
  },
  {
    id: 'manzanate',
    name: 'Manzanate',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 90,
    impact: 100,
    description: 'Apple, fresh green-fruity',
  },
  {
    id: 'safraleine',
    name: 'Safraleine',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 168,
    impact: 250,
    description: 'Saffron, leather, smoky spicy',
  },
  {
    id: 'cyclogalbanate',
    name: 'Cyclogalbanate',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    description: 'Galbanum-green, violet fresh',
  },
  {
    id: 'anise_star_eo',
    name: 'Anise Star EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 18,
    impact: 125,
    description: 'Sweet anise, liquorice herbal',
  },
  {
    id: 'coriander_eo',
    name: 'Coriander EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 8,
    impact: 145,
    description: 'Spicy-woody citrusy, fresh herb',
  },
  {
    id: 'aniseed_eo',
    name: 'Aniseed EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 18,
    impact: 120,
    description: 'Anise, sweet liquorice',
  },
  {
    id: 'peppermint_eo',
    name: 'Peppermint EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 16,
    impact: 400,
    description: 'Fresh mint, cool mentholic',
  },
  {
    id: 'oregano_eo',
    name: 'Oregano EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 15,
    impact: 140,
    description: 'Herbal, thyme-like, Mediterranean',
  },
  {
    id: 'rosemary_eo',
    name: 'Rosemary EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 130,
    description: 'Fresh camphorous, herbal',
  },
  {
    id: 'camphor_eo',
    name: 'Camphor EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 350,
    description: 'Medicinal camphorous, cool',
  },
  {
    id: 'ginger_eo',
    name: 'Ginger EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 24,
    impact: 200,
    description: 'Spicy-warm ginger, zesty fresh',
  },
  {
    id: 'angelica_root_eo',
    name: 'Angelica Root EO',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 24,
    impact: 150,
    description: 'Earthy musky, slightly celery',
  },
  {
    id: 'clove_bud_eo',
    name: 'Clove Bud EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 188,
    impact: 180,
    ifraLimit: 0.5,
    description: 'Warm clove, eugenol-rich — Cat4: 0.5%',
  },
  {
    id: 'peru_balsam_eo',
    name: 'Peru Balsam EO',
    family: 'Misc',
    role: 'Fixative',
    note: 'Base',
    tenacityHours: 400,
    impact: 45,
    ifraLimit: 0.4,
    description: 'Warm balsamic vanilla — IFRA Cat4: 0.4%',
  },
  {
    id: 'safranal',
    name: 'Safranal',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 7.13,
    impact: 3.97,
    description: 'Saffron, hay, slightly leathery',
  },
  {
    id: 'eucalyptus_eo',
    name: 'Eucalyptus EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 370,
    description: 'Fresh medicinal, eucalyptol',
  },
  {
    id: 'sage_eo',
    name: 'Sage EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 12,
    impact: 105,
    description: 'Herbal, camphoraceous sage',
  },
  {
    id: 'black_pepper_eo',
    name: 'Black Pepper EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 40,
    impact: 150,
    description: 'Spicy, warm dry pepper',
  },
  {
    id: 'pink_peppercorn_eo',
    name: 'Pink Peppercorn EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 140,
    impact: 100,
    description: 'Fresh spicy, slightly fruity pepper',
  },
  {
    id: 'spearmint_eo',
    name: 'Spearmint EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 36,
    impact: 230,
    description: 'Minty sweet, gentler than peppermint',
  },
  {
    id: 'nutmeg_eo',
    name: 'Nutmeg EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 48,
    impact: 90,
    description: 'Warm spice, woody slightly floral',
  },
  {
    id: 'white_thyme_eo',
    name: 'White Thyme EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 24,
    impact: 570,
    description: 'Herbal thymol, medicinal',
  },
  {
    id: 'allspice_eo',
    name: 'Allspice EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 24,
    impact: 130,
    description: 'Warm clove-cinnamon-nutmeg blend',
  },
  {
    id: 'fennel_eo',
    name: 'Fennel EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    subFamily: 'Anisic',
    cas: '8006-84-6',
    tenacityHours: 24,
    impact: 180,
    description: 'Anise-like herbal, slightly sweet',
    percepFactor: 1.8,
    dataSource: 'PW',
  },
  {
    id: 'basil_eo',
    name: 'Basil EO',
    family: 'Lav+Aromatic',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 4,
    impact: 150,
    description: 'Fresh green herbal, anise-basil facets',
  },
  {
    id: 'calone',
    name: 'Calone',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    cas: '28940-11-6',
    tenacityHours: 600,
    impact: 800,
    description: 'Ozonic marine watermelon — use ultra-sparingly',
  },
  {
    id: 'cardamom_eo',
    name: 'Cardamom EO',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 12,
    impact: 300,
    description: 'Warm spicy, slightly sweet, slightly floral',
  },
  {
    id: 'cashmeran',
    name: 'Cashmeran',
    family: 'Musks',
    role: 'Heart',
    note: 'Heart',
    cas: '33704-61-9',
    tenacityHours: 200,
    impact: 80,
    description: 'Cashmere-like warm woody musk, spicy edge',
  },
  {
    id: 'cedramber_iff',
    name: 'Cedramber IFF',
    family: 'Woods',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 125,
    impact: 120,
    description: 'Cedarwood-amber, dry woody diffusive',
  },
  {
    id: 'cinnamon_bark_eo',
    name: 'Cinnamon Bark EO',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 140,
    impact: 150,
    ifraLimit: 0.2,
    description: 'Warm cinnamon, sweet spicy — Cat4: 0.2%',
  },
  {
    id: 'cis3_hexenol',
    name: 'Cis-3-Hexenol',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    cas: '928-96-1',
    tenacityHours: 4,
    impact: 700,
    description: 'Fresh-cut green grass, leafy, powerful',
  },
  {
    id: 'cis3_hexenyl_sal',
    name: 'Cis-3-Hexenyl Salicylate',
    family: 'Aldehydes+Esters',
    role: 'Heart',
    note: 'Heart',
    cas: '65405-77-8',
    tenacityHours: 216,
    impact: 90,
    description: 'Green leafy floral, fresh herbal',
  },
  {
    id: 'cyclamen_aldehyde',
    name: 'Cyclamen Aldehyde',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    cas: '103-95-7',
    tenacityHours: 72,
    impact: 75,
    description: 'Violet-lilac aldehydic, watery cyclamen',
  },
  {
    id: 'damascone_alpha',
    name: 'Damascone Alpha',
    family: 'Rose',
    role: 'Heart',
    note: 'Heart',
    cas: '24720-09-0',
    tenacityHours: 60,
    impact: 700,
    description: 'Rose fruity, apple-rose, highly diffusive',
  },
  {
    id: 'damascone_beta',
    name: 'Damascone Beta',
    family: 'Rose',
    role: 'Heart',
    note: 'Heart',
    cas: '23726-93-4',
    tenacityHours: 190,
    impact: 450,
    description: 'Rose spicy woody, dried-rose character',
  },
  {
    id: 'dihydro_myrcenol',
    name: 'Dihydro Myrcenol',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    cas: '18479-58-8',
    tenacityHours: 16,
    impact: 100,
    description: 'Fresh citrus-lime, clean, pine facet',
  },
  {
    id: 'floralozone',
    name: 'Floralozone',
    family: 'Misc',
    role: 'Heart',
    note: 'Heart',
    cas: '67634-15-5',
    tenacityHours: 80,
    impact: 100,
    description: 'Ozonic floral, cyclohexyl, watery fresh',
  },
  {
    id: 'frankincense_eo',
    name: 'Frankincense EO',
    family: 'Naturals',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 188,
    impact: 50,
    description: 'Incense, citrus-resinous, balsamic olibanum',
  },
  {
    id: 'geranyl_acetate',
    name: 'Geranyl Acetate',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    cas: '105-87-3',
    tenacityHours: 24,
    impact: 125,
    description: 'Rose-geranium fruity, sweet waxy',
  },
  {
    id: 'labdanum_abs',
    name: 'Labdanum Abs',
    family: 'Naturals',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 100,
    impact: 200,
    description: 'Amber cistus, sweet animalic, complex',
  },
  {
    id: 'labdanum_eo',
    name: 'Labdanum EO',
    family: 'Naturals',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 400,
    impact: 600,
    description: 'Warm amber, cistus, slightly earthy resinous',
  },
  {
    id: 'labdanum_resinoid',
    name: 'Labdanum Resinoid',
    family: 'Naturals',
    role: 'Heart',
    note: 'Heart',
    tenacityHours: 65,
    impact: 400,
    description: 'Amber cistus, sweet-earthy, balsamic',
  },
  {
    id: 'phenyl_ethyl_acetate',
    name: 'Phenyl Ethyl Acetate',
    family: 'Aldehydes+Esters',
    role: 'Modifier',
    note: 'Top',
    cas: '103-45-7',
    tenacityHours: 16,
    impact: 90,
    description: 'Rose-honey fruity, sweet floral',
  },
  {
    id: 'stemone',
    name: 'Stemone',
    family: 'Misc',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 16,
    impact: 1000,
    description: 'Grapefruit-violet, citrus-iris, highly diffusive',
  },
  {
    id: 'cedarwood_virginian_eo',
    name: 'Cedarwood Virginian EO',
    family: 'Woods',
    role: 'Modifier',
    note: 'Top',
    tenacityHours: 32,
    impact: 90,
    description: 'Dry cedar, pencil-shavings, warm woody',
  },
];
